#servlet端口号 + 项目名 + jsp热部署
server:
  port: 8989
  servlet:
    context-path: /springboot-layui-monthly
    # jsp 热部署 配置
    jsp:
      init-parameters:
        development: true
spring:
  #配置数据库的连接信息 + 日期转换
  datasource:
    url: jdbc:mysql://localhost:3306/root?useUnicode=true&characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  # 全局日期格式 -- 优先级低
  jackson:
    date-format: yyyy-MM-dd
    time-zone: GMT+8
  # 文件上传
  resources:
    static-locations: file:${imgPath}
    servlet:
      multipart:
        max-request-size: 3MB  #设置总的请求大小
        max-file-size: 2MB   #设置单个文件上传的大小
  #设置一个路径供配置文件和controller共用
  imgPath: d:\\testImg
  #jsp视图 (低版本)
  view:
    prefix/spring:
      view:
        suffix:
#linux -- redis 配置文件
  redis:
    lettuce:
      pool:
        max-active: 500
        max-idle: 50
        min-idle: 10
        max-wait: 30000
    #单机(三选一)
    host: 192.168.139.16
    port: 6379
    #哨兵节点(三选一)
    sentinel:
      master: mymaster
      nodes: 192.168.146.26:26379,192.168.146.27:26379,192.168.146.28:26379
    #集群(三选一)
    cluster:
      max-redirects: 3
      nodes: [ 192.168.146.31:6379,92.168.146.32:6379,92.168.146.33:6379,92.168.146.34:6379,92.168.146.35:6379,92.168.146.36:6379 ]
#给实体起别名，设置映射文件的路径。
mybatis-plus:
  type-aliases-package: com.baizhi.entity
  mapper-locations: classpath:com/baizhi/mapper/*.xml
